# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json
# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: edge
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: America/Los_Angeles
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /samples/aws-sqs
    target-branch: edge
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: America/Los_Angeles
    groups:
      gomod:
        patterns:
          - "*"

  - package-ecosystem: devcontainers
    directory: /
    target-branch: edge
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: America/Los_Angeles

  - package-ecosystem: npm
    directories:
      - /playwright
      - /samples/dapr/nodeapp
      - /samples/demo
      - /samples/demo/client
    target-branch: edge
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: America/Los_Angeles
    groups:
      npm:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-major

  - package-ecosystem: nuget
    directories:
      - /samples/aws
      - /samples/dapr/ui
    target-branch: edge
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: America/Los_Angeles
    groups:
      nuget:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /samples/volumes/src
    target-branch: edge
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: America/Los_Angeles
    groups:
      pip:
        patterns:
          - "*"

  - package-ecosystem: gitsubmodule
    directory: /
    target-branch: edge
    schedule:
      interval: weekly
      day: monday
      time: "07:00"
      timezone: America/Los_Angeles
    groups:
      gitsubmodule:
        patterns:
          - "*"
