version: 2

multi-ecosystem-groups:
  weekly-all-deps:
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"
    target-branch: "edge"
    multi-ecosystem-group: "weekly-all-deps"
    patterns:
      - "*"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/samples/aws-sqs"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"
    target-branch: "edge"
    multi-ecosystem-group: "weekly-all-deps"
    patterns:
      - "*"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"
    target-branch: "edge"
    multi-ecosystem-group: "weekly-all-deps"
    patterns:
      - "*"
  - package-ecosystem: "npm"
    directories:
      - "/playwright"
      - "/samples/dapr/nodeapp"
      - "/samples/demo"
      - "/samples/demo/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"
    target-branch: "edge"
    multi-ecosystem-group: "weekly-all-deps"
    patterns:
      - "*"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "nuget"
    directories:
      - "/samples/aws"
      - "/samples/dapr/ui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"
    target-branch: "edge"
    multi-ecosystem-group: "weekly-all-deps"
    patterns:
      - "*"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/samples/volumes/src"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "America/Los_Angeles"
    target-branch: "edge"
    multi-ecosystem-group: "weekly-all-deps"
    patterns:
      - "*"
    groups:
      all:
        patterns:
          - "*"
