apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env: 
        - name: CONNECTION_POSTGRES_HOST
          value: {{ .Values.datastore.postgres.host }}
        - name: CONNECTION_POSTGRES_PORT
          value: {{ .Values.datastore.postgres.port }}
        - name: CONNECTION_POSTGRES_USER
          value: {{ .Values.datastore.postgres.username }}
        - name: CONNECTION_POSTGRES_DB
          value: {{ .Values.datastore.postgres.database }}
        - name: CONNECTION_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        ports:
        - containerPort: 3000