# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
---
name: Build samples

on:
  workflow_dispatch:
  push:
    branches:
      - edge
      - v*.*
  pull_request:
    branches:
      - edge
      - v*.*
    paths:
      - samples/**
      - .github/workflows/build.yaml

permissions: {}

env:
  VERSION: latest
  CONTAINER_REGISTRY: ghcr.io/radius-project

jobs:
  build-ghcr:
    name: Build and push sample images to GHCR
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - directory: samples/demo/
            image: samples/demo
          - directory: samples/dapr/ui/
            image: samples/dapr-frontend
          - directory: samples/dapr/nodeapp/
            image: samples/dapr-backend
          - directory: samples/aws/
            image: samples/aws
          - directory: samples/aws-sqs/
            image: samples/aws-sqs
          - directory: samples/volumes/
            image: samples/volumes
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push ${{ matrix.image }}
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: ./${{ matrix.directory }}
          push: ${{ github.event_name == 'push' && true || false }}
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ matrix.image }}:${{ env.VERSION }}
